BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
    .string "Lucas, feliz aniversário! Que seu dia\nseja épico e que você continue\lsendo esse treinador incrível que é\luma verdadeira lenda em Hoenn!$"
BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
    .string "Parabéns, Lucas! Você é o mestre\nPokémon que sempre quis ser! Hoje é\lo seu dia, Lucas! Sua jornada apenas\lcomeçou. Um brinde ao Lucas! O\lmundo Pokémon celebra você! Feliz\l23 de Maio, Lucas! O seu presente\lestá esperando por você! Feliz\laniversário, Lucas! Que todos os\lseus desejos se realizem!$"
BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
    .string "Feliz 23 de maio, Lucas! Prepare-se\npara grandes batalhas! Feliz 23 de\lmaio, Lucas! Que todos os seus\ldesejos se realizem! Feliz\laniversário, Lucas! Você é o Mestre\lPokémon que sempre quis ser! Lucas,\lvocê é o melhor! O seu presente\lestá te esperando! Um brinde ao\lLucas! O seu presente está te\lesperando! Feliz aniversário, Lucas!\lVocê é o campeão do nosso coração!\lParabéns, Lucas! Capture todos os\lPokémon hoje!$"
