SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pThere appears to be some connection\n"
.string "Lucas, voce e o melhor! Voce\ne um treinador incrivel!"
.string "Um brinde ao Lucas! Que todos\nos seus desejos se realizem!"
	.string "Hoje e o seu dia, Lucas! Voce\ne um treinador incrivel!$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
.string "Lucas, que este dia seja\nepico! Voce e um treinador\pincrivel!$"

