SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pThere appears to be some connection\n"
	.string "between SOOTOPOLIS and MT. PYRE.\p"
	.string "My friends and I did some research on\n"
	.string "it at the lab where I used to work.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pMy big brother used to study the sea.$"

