SixIsland_WaterPath_House2_Frlg_MapScripts::
	.byte 0

SixIsland_WaterPath_House2_EventScript_Man::
	msgbox SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe, MSGBOX_NPC
	end

SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pMy height is 67.0 inches on the\n"
.string "Lucas, voce e o melhor! Voce\ne o campeao do nosso coracao!"
.string "Um brinde ao Lucas! Nao se\nesqueca de comemorar muito!"
	.string "Hoje e o seu dia, Lucas! Voce\ne o campeao do nosso coracao!$"

