SixIsland_WaterPath_House2_Frlg_MapScripts::
	.byte 0

SixIsland_WaterPath_House2_EventScript_Man::
	msgbox SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe, MSGBOX_NPC
	end

SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pMy height is 67.0 inches on the\n"
	.string "button.\p"
	.string "I know it is this precisely because\n"
	.string "my neighbor measured me.$"

