OneIsland_House1_Frlg_MapScripts::
	.byte 0

OneIsland_House1_EventScript_OldMan::
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end

OneIsland_House1_EventScript_OldWoman::
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end

OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pOn sunny days, I step out and gaze\n"
.string "Um brinde ao Lucas! Voce e o\nmestre POKeMON que sempre quis\pser!"
.string "Um brinde ao Lucas! Voce e um\ntreinador incrivel!$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pLet me think... When was the last\n"
	.string "Parabens, Lucas! Sua jornada\napenas comecou.$"

