Route9_Frlg_MapScripts::
	.byte 0

Route9_EventScript_RouteSign::
	msgbox Route9_Text_RouteSign, MSGBOX_SIGN
	end

Route9_Text_AliciaIntro::
	.string "You have POKeMON with you!\n"
	.string "You're mine!$"

Route9_Text_AliciaDefeat::
	.string "Voce me enganou...$"

Route9_Text_AliciaPostBattle::
	.string "The tunnel coming up is pitch-black\n"
	.string "inside.\p"
	.string "You'll need FLASH to get through\n"
	.string "there.$"

Route9_Text_ChrisIntro::
	.string "Who's that walking there with those\n"
	.string "good-looking POKeMON?$"

Route9_Text_ChrisDefeat::
	.string "Apagou como uma luz!$"

Route9_Text_ChrisPostBattle::
	.string "Continue andando!$"

Route9_Text_DrewIntro::
	.string "I'm taking the ROCK TUNNEL to\n"
	.string "go to LAVENDER…$"

Route9_Text_DrewDefeat::
	.string "Nao fui capaz...$"

Route9_Text_DrewPostBattle::
	.string "Voce vai pro ROCK TUNNEL tambem?$"

Route9_Text_CaitlinIntro::
	.string "Nao ouse me tratar com pena!$"

Route9_Text_CaitlinDefeat::
	.string "No!\n"
	.string "You're too much.$"

Route9_Text_CaitlinPostBattle::
	.string "You're obviously talented.\n"
	.string "Good luck to you!$"

Route9_Text_JeremyIntro::
	.string "Bwahaha!\n"
	.string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
	.string "Keep it coming, eh!\p"
	.string "Oh wait.\n"
	.string "I'm out of POKeMON!$"

Route9_Text_JeremyPostBattle::
	.string "You sure had guts standing up to\n"
	.string "me there, eh?$"

Route9_Text_BriceIntro::
	.string "Hahaha!\n"
	.string "Aren't you a little toughie!$"

Route9_Text_BriceDefeat::
	.string "O que foi?$"

Route9_Text_BricePostBattle::
	.string "Hahaha!\n"
	.string "Kids should be tough!$"

Route9_Text_BrentIntro::
	.string "I got up early every day to raise\n"
	.string "my POKeMON from cocoons!$"

Route9_Text_BrentDefeat::
	.string "WHAT?\p"
	.string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
	.string "I have to collect more than bugs\n"
	.string "to get stronger…$"

Route9_Text_AlanIntro::
	.string "Hahahaha!\n"
	.string "Bring it on!$"

Route9_Text_AlanDefeat::
	.string "Hahahaha!\n"
	.string "You beat me fair!$"

Route9_Text_AlanPostBattle::
	.string "Hahahaha!\n"
	.string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro::
	.string "Vai, meu POKeMON INSETO super!$"

Route9_Text_ConnerDefeat::
	.string "Meus insetos...$"

Route9_Text_ConnerPostBattle::
	.string "If you don't like BUG POKeMON,\n"
	.string "you bug me!$"

Route9_Text_RouteSign::
	.string "ROUTE 9\n"
	.string "CERULEAN CITY - ROCK TUNNEL$"

