import re

with open('data/maps/LittlerootTown/scripts.inc', 'r', encoding='utf-8') as f:
    text = f.read()

replacements = {
    r'"Feliz aniversario, Lucas! Voce e um amigo incrivel.\\pMOM: {PLAYER}, we\'re here, honey!\\p"': r'"Feliz aniversario, Lucas! Você é um amigo incrível.\\pMÃE: {PLAYER}, chegamos, querido!\\p"',
    r'"It must be tiring riding with our things\\n"': r'"Deve ter sido cansativo viajar com as nossas coisas\\n"',
    r'"in the moving truck.\\p"': r'"no caminhão de mudança.\\p"',
    r'"Well, this is LITTLEROOT TOWN.\\p"': r'"Bem, esta é a CIDADE DE LITTLEROOT.\\p"',
    r'"How do you like it\?\\n"': r'"O que achou\?\\n"',
    r'"This is our new home!\\p"': r'"Esta é a nossa nova casa!\\p"',
    r'"It has a quaint feel, but it seems to be\\n"': r'"Tem um clima pitoresco, mas parece ser\\n"',
    r'"an easy place to live, don\'t you think\?\\p"': r'"um lugar tranquilo para viver, não acha\?\\p"',
    r'"And, you get your own room, {PLAYER}!\\n"': r'"E você terá seu próprio quarto, {PLAYER}!\\n"',
    r'"Let\'s go inside.\$"': r'"Vamos entrar.$"',
    r'"MOM: Wait, {PLAYER}!\$"': r'"MÃE: Espere, {PLAYER}!$"',
    r'"Hoje e o seu dia, Lucas! Aproveite a aventura.\\pMOM: {PLAYER}! {PLAYER}! Did you\\n"': r'"Hoje é o seu dia, Lucas! Aproveite a aventura.\\pMÃE: {PLAYER}! {PLAYER}! Você já se\\n"',
    r'"introduce yourself to PROF. BIRCH\?\\p"': r'"apresentou ao PROF. BIRCH?\\p"',
    r'"Oh! What an adorable POKeMON!\\n"': r'"Oh! Que POKéMON adorável!\\n"',
    r'"You got it from PROF. BIRCH. How nice!\\p"': r'"Você ganhou do PROF. BIRCH. Que legal!\\p"',
    r'"You\'re your father\'s child, all right.\\n"': r'"Você é mesmo filho do seu pai.\\n"',
    r'"You look good together with POKeMON!\\p"': r'"Você fica muito bem com POKéMON!\\p"',
    r'"Here, honey! If you\'re going out on an\\n"': r'"Aqui, querido! Se vai sair em uma\\n"',
    r'"adventure, wear these RUNNING SHOES.\\p"': r'"aventura, use estes TÊNIS DE CORRIDA.\\p"',
    r'"They\'ll put a zip in your step!\$"': r'"Eles vão dar um gás nos seus passos!$"',
    r'"MOM: {PLAYER}, those shoes came with\\n"': r'"MÃE: {PLAYER}, esses tênis vieram com\\n"',
    r'"instructions.\\p"': r'"instruções.\\p"',
    r'"“Press the B Button while wearing these\\n"': r'"“Pressione o Botão B enquanto usa estes\\n"',
    r'"RUNNING SHOES to run extra-fast!\\p"': r'"TÊNIS DE CORRIDA para correr super rápido!\\p"',
    r'"“Slip on these RUNNING SHOES and race\\n"': r'"“Coloque estes TÊNIS DE CORRIDA e corra\\n"',
    r'"in the great outdoors!”\$"': r'"ao ar livre!”$"',
    r'"Hoje e o seu dia, Lucas! Aproveite a aventura.\\p… … … … … … … …\\n"': r'"Hoje é o seu dia, Lucas! Aproveite a aventura.\\p… … … … … … … …\\n"',
    r'"To think that you have your very own\\n"': r'"Pensar que agora você tem o seu próprio\\n"',
    r'"POKeMON now…\\l"': r'"POKéMON...\\l"',
    r'"Your father will be overjoyed.\\p"': r'"Seu pai vai ficar muito feliz.\\p"',
    r'"…But please be careful.\\n"': r'"…Mas, por favor, tome cuidado.\\n"',
    r'"If anything happens, you can come home.\\p"': r'"Se acontecer qualquer coisa, pode voltar.\\p"',
    r'"Go on, go get them, honey!\$"': r'"Vai lá, mostre o que sabe, querido!$"',
    r'"If you use a PC, you can store items\\n"': r'"Se você usar um PC, pode guardar itens\\n"',
    r'"and POKeMON.\\p"': r'"e POKéMON.\\p"',
    r'"The power of science is staggering!\$"': r'"O poder da ciência é incrível!$"',
    r'"Parabens, Lucas! Que sua jornada seja epica.\\pPROF. BIRCH spends days in his LAB\\n"': r'"Parabéns, Lucas! Que sua jornada seja épica.\\pPROF. BIRCH passa dias no LABORATÓRIO\\n"',
    r'"studying, then he\'ll suddenly go out in\\l"': r'"estudando, e de repente sai pela\\l"',
    r'"the wild to do more research…\\p"': r'"natureza para pesquisar mais…\\p"',
    r'"When does PROF. BIRCH spend time\\n"': r'"Quando o PROF. BIRCH passa tempo\\n"',
    r'"at home\?\$"': r'"em casa?$"',
    r'"Hoje e o seu dia, Lucas! Aproveite a aventura.\\pUm, um, um!\\p"': r'"Hoje é o seu dia, Lucas! Aproveite a aventura.\\pUm, um, um!\\p"',
    r'"If you go outside and go in the grass,\\n"': r'"Se você for lá fora na grama,\\n"',
    r'"wild POKeMON will jump out!\$"': r'"POKéMON selvagens vão pular!$"',
    r'"Parabens, Lucas! Que sua jornada seja epica.\\pIt\'s dangerous if you don\'t have\\n"': r'"Parabéns, Lucas! Que sua jornada seja épica.\\pÉ perigoso se você não tiver\\n"',
    r'"your own POKeMON.\$"': r'"seu próprio POKéMON.$"',
    r'"Parabens, Lucas! Que sua jornada seja epica.\\pUm, hi!\\p"': r'"Parabéns, Lucas! Que sua jornada seja épica.\\pAh, oi!\\p"',
    r'"There are scary POKeMON outside!\\n"': r'"Existem POKéMON assustadores lá fora!\\n"',
    r'"I can hear their cries!\\p"': r'"Eu consigo ouvir os gritos deles!\\p"',
    r'"I want to go see what\'s going on,\\n"': r'"Queria ir ver o que está acontecendo,\\n"',
    r'"but I don\'t have any POKeMON…\\p"': r'"mas não tenho nenhum POKéMON…\\p"',
    r'"Can you go see what\'s happening\\n"': r'"Pode ir ver o que está acontecendo\\n"',
    r'"for me\?\$"': r'"por mim?$"',
    r'"Hoje e o seu dia, Lucas! Aproveite a aventura.\\pYou saved PROF. BIRCH!\\n"': r'"Hoje é o seu dia, Lucas! Aproveite a aventura.\\pVocê salvou o PROF. BIRCH!\\n"',
    r'"I\'m so glad!\$"': r'"Que alívio!$"',
    r'"Hoje e o seu dia, Lucas! Aproveite a aventura.\\pAre you going to catch POKeMON\?\\n"': r'"Hoje é o seu dia, Lucas! Aproveite a aventura.\\pVocê vai pegar POKéMON?\\n"',
    r'"Good luck!\$"': r'"Boa sorte!$"',
    r'"LITTLEROOT TOWN\\n"': r'"CIDADE DE LITTLEROOT\\n"',
    r'"“A town that can\'t be shaded any hue.”\$"': r'"“Uma cidade que não pode ser sombreada por nenhuma cor.”$"',
    r'"Parabens, Lucas! Que sua jornada seja epica.\\pPROF. BIRCH\'S POKeMON LAB\$"': r'"Parabéns, Lucas! Que sua jornada seja épica.\\pLAB. DE POKéMON DO PROF. BIRCH$"',
    r'"Hoje e o seu dia, Lucas! Aproveite a aventura.\\pPROF. BIRCH\'S HOUSE\$"': r'"Hoje é o seu dia, Lucas! Aproveite a aventura.\\pCASA DO PROF. BIRCH$"',
    r'"Feliz aniversario, Lucas! Voce e um amigo incrivel.\\pPROF. BIRCH: Well, well, {PLAYER}{KUN}!\\n"': r'"Feliz aniversário, Lucas! Você é um amigo incrível.\\pPROF. BIRCH: Ora, ora, {PLAYER}{KUN}!\\n"',
    r'"That was good work out there!\\p"': r'"Você mandou muito bem lá fora!\\p"',
    r'"I knew there was something special\\n"': r'"Eu sabia que tinha algo de especial\\n"',
    r'"about you when I first saw you,\\l"': r'"em você quando o vi,\\l"',
    r'"but I never expected this.\\p"': r'"mas eu não esperava tanto.\\p"',
    r'"Oh, yes. Do you still have the POKeDEX\\n"': r'"Ah, sim. Você ainda tem a POKéDEX\\n"',
    r'"I gave you\?\\p"': r'"que eu te dei?\\p"',
    r'"I have something to show you.\\n"': r'"Eu tenho algo para te mostrar.\\n"',
    r'"Let\'s go to my LAB.\$"': r'"Vamos ao meu LABORATÓRIO.$"',
}

for k, v in replacements.items():
    text = re.sub(k, v, text)

with open('data/maps/LittlerootTown/scripts.inc', 'w', encoding='utf-8') as f:
    f.write(text)
