Route8_Frlg_MapScripts::
	.byte 0

Route8_EventScript_UndergroundPathSign::
	msgbox Route8_Text_UndergroundPathSign, MSGBOX_SIGN
	end

Route8_Text_AidanIntro::
	.string "You look good at POKeMON, but how\n"
	.string "is your chemistry grade?$"

Route8_Text_AidanDefeat::
	.string "Ow!\n"
	.string "Meltdown!$"

Route8_Text_AidanPostBattle::
	.string "Sou melhor na escola que nisso!$"

Route8_Text_StanIntro::
	.string "All right!\n"
	.string "Let's play a game!$"

Route8_Text_StanDefeat::
	.string "Drat!\n"
	.string "Came up short!$"

Route8_Text_StanPostBattle::
	.string "As coisas nao deram certo hoje.$"

Route8_Text_GlennIntro::
	.string "You should be informed.\n"
	.string "You need strategy to win at this!$"

Route8_Text_GlennDefeat::
	.string "Nao e logico!$"

Route8_Text_GlennPostBattle::
	.string "Go with GRIMER first…and…\n"
	.string "…and…then…$"

Route8_Text_PaigeIntro::
	.string "Gosto do NIDORAN, entao coleciono!$"

Route8_Text_PaigeDefeat::
	.string "Why?\n"
	.string "Why??$"

Route8_Text_PaigePostBattle::
	.string "When POKeMON grow up, they get\n"
	.string "ugly! They shouldn't evolve.$"

Route8_Text_LeslieIntro::
	.string "Escola e legal, POKeMON tambem.$"

Route8_Text_LeslieDefeat::
	.string "You made it clear to me that\n"
	.string "I should stick with school.$"

Route8_Text_LesliePostBattle::
	.string "I was planning on getting some\n"
	.string "fresh air for a change, but…\p"
	.string "We're stuck here because of the\n"
	.string "gates at SAFFRON.$"

Route8_Text_AndreaIntro::
	.string "MEOWTH is so cute, meow, meow,\n"
	.string "meow!$"

Route8_Text_AndreaDefeat::
	.string "Miau!$"

Route8_Text_AndreaPostBattle::
	.string "I think PIDGEY and RATTATA are\n"
	.string "cute, too!$"

Route8_Text_MeganIntro::
	.string "We must look silly standing here\n"
	.string "like this.$"

Route8_Text_MeganDefeat::
	.string "Look what you did to my poor, cute\n"
	.string "POKeMON!$"

Route8_Text_MeganPostBattle::
	.string "SAFFRON's gatekeeper won't let us\n"
	.string "go through.\p"
	.string "I know he's doing his job, but I\n"
	.string "think he's mean.$"

Route8_Text_RichIntro::
	.string "Sou um cara viajante e jogador!$"

Route8_Text_RichDefeat::
	.string "Perdi a grande chance!$"

Route8_Text_RichPostBattle::
	.string "Playing games and POKeMON are like\n"
	.string "eating peanuts! I just can't stop!$"

Route8_Text_JuliaIntro::
	.string "What's a cute, round, and fluffy\n"
	.string "POKeMON?$"

Route8_Text_JuliaDefeat::
	.string "Stop!\p"
	.string "Don't be so mean to my CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
	.string "I read that CLEFAIRY evolves when\n"
	.string "it's exposed to a MOON STONE.\p"
	.string "I read that in a POKeMON JOURNAL.\n"
	.string "I wonder if it's true?$"

Route8_Text_UndergroundPathSign::
	.string "UNDERGROUND PATH\n"
	.string "CELADON CITY - LAVENDER TOWN$"

Route8_Text_EliIntro::
	.string "ELI: Twin power is fantastic.\n"
	.string "Did you know?$"

Route8_Text_EliDefeat::
	.string "ELI: But…\n"
	.string "We used our twin power…$"

Route8_Text_EliPostBattle::
	.string "ELI: I caught my POKeMON with\n"
	.string "ANNE!$"

Route8_Text_EliNotEnoughMons::
	.string "ELI: We can't battle if you don't\n"
	.string "have two POKeMON.$"

Route8_Text_AnneIntro::
	.string "ANNE: We'll shock you with our twin\n"
	.string "power!$"

Route8_Text_AnneDefeat::
	.string "ANNE: Nosso poder gemeo...$"

Route8_Text_AnnePostBattle::
	.string "ANNE: I'm raising POKeMON with\n"
	.string "ELI.$"

Route8_Text_AnneNotEnoughMons::
	.string "ANNE: Hi, hi! Let's battle!\n"
	.string "But bring two POKeMON.$"

Route8_Text_RicardoIntro::
	.string "Minha bike ta com problema, cara.$"

Route8_Text_RicardoDefeat::
	.string "Aww, man.\n"
	.string "I'm not into this.$"

Route8_Text_RicardoPostBattle::
	.string "I got grass caught up in my\n"
	.string "spokes, man.$"

Route8_Text_JarenIntro::
	.string "Clear the way, or I'll run you\n"
	.string "down!$"

Route8_Text_JarenDefeat::
	.string "Fala serio, garoto?$"

Route8_Text_JarenPostBattle::
	.string "Don't think you're all special and\n"
	.string "all just because of this.$"
