gText_Birch_Welcome::
	.string "Ah, entao voce e o tal do Lucas!\p"
	.string "Hoje e um dia muito especial, e eu\n"
	.string "acredito que voce ja sabe o como\l"
	.string "isso funciona.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Isto e o que chamamos de POKeMON.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Neste mundo, voce vai encontrar\n"
	.string "varios POKeMON e pessoas.\p"
	.string "Hoje e o seu aniversario, e nao ha\n"
	.string "momento melhor para iniciar isso!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Mas para confirmar...$"

gText_Birch_BoyOrGirl::
	.string "Voce e um garoto?\n"
	.string "Ou e uma garota?$"

gText_Birch_WhatsYourName::
	.string "Entendido.\n"
	.string "E qual e o seu nome mesmo?$"

gText_Birch_SoItsPlayer::
	.string "Entao o seu nome e {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Perfeito!\p"
	.string "Voce e o {PLAYER}{KUN} que acabou de\n"
	.string "se mudar para LITTLEROOT.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Tudo pronto?\p"
	.string "BOA SORTE NA SUA JORNADA,\n"
	.string "e FELIZ ANIVERSARIO!\p"
	.string "$"
