gText_Birch_Welcome::
    .string "Ah! Entäo você é o tal do Lucas!\n"
    .string "Hoje é um dia muito especial, e eu\l"
    .string "acredito que você já sabe muito bem\l"
    .string "como o mundo funciona.\p$"

gText_Birch_Pokemon::
    .string "$"

gText_Birch_MainSpeech::
    .string "Sendo assim, näo vou te enrolar\n"
    .string "com explicaçöes chatas.\p"
    .string "BOA SORTE NA SUA JORNADA, e\n"
    .string "FELIZ ANIVERSáRIO, Lucas!\p$"

gText_Birch_AndYouAre::
    .string "$"

gText_Birch_BoyOrGirl::
    .string "Você é menino ou menina?$"

gText_Birch_WhatsYourName::
    .string "Assine seu nome aqui, por favor.$"

gText_Birch_SoItsPlayer::
    .string "Entäo é {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
    .string "Ah, claro! Me lembrei.\n"
    .string "Tudo pronto, Lucas!$"

gText_Birch_AreYouReady::
    .string "Sua lenda começa agora!\n"
    .string "Pule no caminhäo e vá!\p$"
