Text_PictureBookShelf:
	.string "There's a set of POKeMON picture books.$"

Text_BookShelf:
	.string "Esta cheio de todo tipo de livro.$"

Text_PokemonCenterBookShelf:
	.string "Revistas POKeMON!\n"
	.string "POKeMON PAL…\p"
	.string "POKeMON HANDBOOK…\n"
	.string "ADORABLE POKeMON…$"

Text_Vase:
	.string "Este vaso parece caro...\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "Esta vazio.\lCade o bolo do Lucas?$"

Text_ShopShelf:
	.string "The shelves brim with all sorts of\n"
	.string "POKeMON merchandise.$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
