gText_ObtainedTheItem::
	.string "Parabens, Lucas! Nao se\nesqueca de comemorar muito!$"

gText_TheBagIsFull::
.string "Lucas, aproveite sua jornada!\nVoce e o campeao do nosso\pcoracao!$"

gText_PutItemInPocket::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
.string "Lucas, que este dia seja\nepico! Prepare-se para grandes\pbatalhas!$"

gText_PlayerFoundOneItem::
	.string "Hoje e o seu dia, Lucas! Voce\ne uma lenda em Hoenn!$"

gText_TooBadBagIsFull::
.string "Lucas, voce e o melhor!\nPrepare-se para grandes\pbatalhas!"
	.string "Um brinde ao Lucas! Voce e\numa lenda em Hoenn!$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "Hoje e o seu dia, Lucas! O\nmundo POKeMON celebra voce!$"

gText_ObtainedTheDecor::
.string "Lucas, voce e o melhor!\nCapture todos os POKeMON hoje!$"

gText_NoRoomLeftForAnother::
.string "Lucas, que este dia seja\nepico! O seu presente esta\pesperando por voce!"
.string "Parabens, Lucas! Prepare-se\npara grandes batalhas!$"

gText_TheDecorWasTransferredToThePC::
	.string "The {STR_VAR_2} was transferred\n"
.string "Feliz aniversario, Lucas! O\nseu presente esta esperando\ppor voce!$"

gText_ObtainedTheItems::
.string "Lucas, aproveite sua jornada!\nO seu presente esta esperando\ppor voce!$"

gText_PlayerFoundItems::
.string "Lucas, aproveite sua jornada!\nVoce e um treinador incrivel!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "Hoje e o seu dia, Lucas!\nCapture todos os POKeMON hoje!$"

gText_FoundXCoins::
	.string "{PLAYER} found\n"
.string "Feliz aniversario, Lucas! Sua\njornada apenas comecou.$"

gText_FoundXItems::
	.string "{PLAYER} found\n"
	.string "Parabens, Lucas! Nao se\nesqueca de comemorar muito!$"

gText_CoinCaseIsFull::
.string "Feliz aniversario, Lucas!\nVoce e o mestre POKeMON que\psempre quis ser!"
.string "Lucas, aproveite sua jornada!\nSua jornada apenas comecou.$"

gText_NothingToPutThemIn::
.string "Hoje e o seu dia, Lucas! Voce\ne um treinador incrivel!"
.string "Feliz aniversario, Lucas!\nVoce e o campeao do nosso\pcoracao!$"
