Text_BootUpPC:
	.string "Feliz aniversario, Lucas!\nVoce e uma lenda em Hoenn!$"

gText_WhichPCShouldBeAccessed::
	.string "Parabens, Lucas! Nao se\nesqueca de comemorar muito!$"

gText_AccessedSomeonesPC::
.string "Um brinde ao Lucas! Nao se\nesqueca de comemorar muito!$"

gText_StorageSystemOpened::
	.string "Um brinde ao Lucas! Sua\njornada apenas comecou.$"

gText_AccessedPlayersPC::
	.string "Parabens, Lucas! Sua jornada\napenas comecou.$"

gText_AccessedLanettesPC::
	.string "Feliz aniversario, Lucas! Que\ntodos os seus desejos se\prealizem!$"

gText_AccessedBillsPC::
	.string "Hoje e o seu dia, Lucas! O\nmundo POKeMON celebra voce!$"
