SafariZone_East_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_East_RestHouse_EventScript_Rocker::
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_Scientist::
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end

SafariZone_East_RestHouse_EventScript_BaldingMan::
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end

SafariZone_East_Text_HowManyDidYouCatch::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pHow many did you catch?\n"
	.string "Feliz 23 de Maio, Lucas! Voce e um treinador incrivel!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pI caught a CHANSEY!\p"
	.string "Feliz aniversario, Lucas! Nao\nse esqueca de comemorar muito!$"

SafariZone_East_Text_TiredFromAllTheFun::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pWhew!\n"
	.string "Um brinde ao Lucas! O mundo\nPOKeMON celebra voce!$"

