UndergroundPath_EastEntrance_Frlg_MapScripts::
	.byte 0

UndergroundPath_EastEntrance_EventScript_Woman::
	msgbox UndergroundPath_EastEntrance_Text_DoYouGoToCeladonDeptStore, MSGBOX_NPC
	end

UndergroundPath_EastEntrance_Text_DoYouGoToCeladonDeptStore::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pThe DEPARTMENT STORE in CELADON\n"
	.string "has a great selection.\p"
	.string "Do you go there very often?$"

