CeladonCity_House1_Frlg_MapScripts::
	.byte 0

CeladonCity_House1_EventScript_RocketChief::
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket1::
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end

CeladonCity_House1_EventScript_Rocket2::
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end

CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pHehehe!\p"
	.string "The slots just reel in the dough,\n"
	.string "big-time!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pCHIEF!\p"
	.string "We just shipped two thousand\n"
	.string "more POKéMON as slot prizes\l"
	.string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pDon't touch the poster at the GAME\n"
	.string "CORNER!\p"
	.string "There's no secret switch behind it!$"

