Route25_Frlg_MapScripts::
	.byte 0

Route25_EventScript_SeaCottageSign::
	msgbox Route25_Text_SeaCottageSign, MSGBOX_SIGN
	end

Route25_EventScript_Man::
	msgbox Route25_Text_AreYouHereAlone, MSGBOX_NPC
	end

Route25_Text_JoeyIntro::
	.string "Local TRAINERS come here to\n"
	.string "practice.$"

Route25_Text_JoeyDefeat::
	.string "Voce e decente.$"

Route25_Text_JoeyPostBattle::
	.string "All POKeMON have weaknesses.\n"
	.string "Even the strongest ones.\p"
	.string "That's why it's best to raise\n"
	.string "POKeMON of different types.$"

Route25_Text_DanIntro::
	.string "Dad took me to a great party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat::
	.string "Nao estou bravo!$"

Route25_Text_DanPostBattle::
	.string "On the S.S. ANNE, I saw TRAINERS\n"
	.string "from around the world.$"

Route25_Text_FlintIntro::
	.string "I'm a cool guy.\n"
	.string "I've got a girlfriend!$"

Route25_Text_FlintDefeat::
	.string "Aww, poxa...$"

Route25_Text_FlintPostBattle::
	.string "Oh, well.\n"
	.string "My girlfriend will cheer me up.$"

Route25_Text_KelseyIntro::
	.string "Hi!\n"
	.string "My boyfriend is cool!$"

Route25_Text_KelseyDefeat::
	.string "Meu condicionamento nao ta bom...$"

Route25_Text_KelseyPostBattle::
	.string "I wish my boyfriend was as good\n"
	.string "as you.$"

Route25_Text_ChadIntro::
	.string "I had this feeling…\n"
	.string "I knew I had to battle you!$"

Route25_Text_ChadDefeat::
	.string "Eu sabia que ia perder tambem!$"

Route25_Text_ChadPostBattle::
	.string "If your POKeMON gets confused,\n"
	.string "switch it out.\p"
	.string "That's a good tactic.$"

Route25_Text_HaleyIntro::
	.string "My friend has many cute POKeMON.\n"
	.string "I'm so jealous!$"

Route25_Text_HaleyDefeat::
	.string "Nao sou tao invejosa assim!$"

Route25_Text_HaleyPostBattle::
	.string "You came from MT. MOON?\n"
	.string "May I have a CLEFAIRY?$"

Route25_Text_FranklinIntro::
	.string "I just got down from MT. MOON,\n"
	.string "but I've still got gas in the tank!$"

Route25_Text_FranklinDefeat::
	.string "Voce trabalhou duro!$"

Route25_Text_FranklinPostBattle::
	.string "Drat!\n"
	.string "A ZUBAT bit me back in that cave.$"

Route25_Text_NobIntro::
	.string "I'm off to see a POKeMANIAC's\n"
	.string "collection at the cape.$"

Route25_Text_NobDefeat::
	.string "You done got me, and real good,\n"
	.string "too!$"

Route25_Text_NobPostBattle::
	.string "The POKeMANIAC sure lives up to\n"
	.string "his name.\p"
	.string "His collection includes many rare\n"
	.string "species of POKeMON.$"

Route25_Text_WayneIntro::
	.string "You're going to see BILL?\n"
	.string "First, we battle!$"

Route25_Text_WayneDefeat::
	.string "Voce e demais.$"

Route25_Text_WaynePostBattle::
	.string "The trail below is a shortcut to\n"
	.string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
	.string "SEA COTTAGE\n"
	.string "BILL lives here!$"

Route25_Text_MistyHighHopesAboutThisPlace::
	.string "This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes about this place.$"

Route25_Text_AreYouHereAlone::
	.string "Hello, are you here alone?\p"
	.string "If you're out at CERULEAN's cape…\n"
	.string "Well, it should be as a couple.$"

