Route17_Frlg_MapScripts::
	.byte 0

Route17_EventScript_ItemsNotice::
	msgbox Route17_Text_WatchOutForDiscardedItems, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips1::
	msgbox Route17_Text_SameSpeciesGrowDifferentRates, MSGBOX_SIGN
	end

Route17_EventScript_TrainerTips2::
	msgbox Route17_Text_PressBToStayInPlace, MSGBOX_SIGN
	end

Route17_EventScript_RouteSign::
	msgbox Route17_Text_RouteSign, MSGBOX_SIGN
	end

Route17_EventScript_BallsNotice::
	msgbox Route17_Text_DontThrowGameThrowBalls, MSGBOX_SIGN
	end

Route17_EventScript_CyclingRoadSign::
	msgbox Route17_Text_CyclingRoadSign, MSGBOX_SIGN
	end

Route17_Text_RaulIntro::
	.string "There's no getting rich quick in\n"
	.string "battling kids.$"

Route17_Text_RaulDefeat::
	.string "Queimado!$"

Route17_Text_RaulPostBattle::
	.string "You can find good stuff lying\n"
	.string "around on CYCLING ROAD.\p"
	.string "There's good money in picking them\n"
	.string "up and selling them.$"

Route17_Text_IsaiahIntro::
	.string "I'm mighty proud of my bod, kiddo.\n"
	.string "Come on!$"

Route17_Text_IsaiahDefeat::
	.string "Uau!$"

Route17_Text_IsaiahPostBattle::
	.string "I could belly-bump you outta\n"
	.string "here!$"

Route17_Text_VirgilIntro::
	.string "Indo pra FUCHSIA?$"

Route17_Text_VirgilDefeat::
	.string "Bater e queimar!$"

Route17_Text_VirgilPostBattle::
	.string "Eu amo correr morro abaixo!$"

Route17_Text_BillyIntro::
	.string "We're BIKERS!\n"
	.string "We rule the roads, man!$"

Route17_Text_BillyDefeat::
	.string "Fumacado!$"

Route17_Text_BillyPostBattle::
	.string "Esta buscando aventura?$"

Route17_Text_NikolasIntro::
	.string "Deixe VOLTORB te eletrizar!$"

Route17_Text_NikolasDefeat::
	.string "Aterrado!$"

Route17_Text_NikolasPostBattle::
	.string "I got my VOLTORB at the abandoned\n"
	.string "POWER PLANT.$"

Route17_Text_ZeekIntro::
	.string "I leveled up my POKeMON, but it\n"
	.string "won't evolve. Why?$"

Route17_Text_ZeekDefeat::
	.string "Ora, voce!$"

Route17_Text_ZeekPostBattle::
	.string "Maybe some POKeMON need element\n"
	.string "STONES to evolve.$"

Route17_Text_JamalIntro::
	.string "Preciso de um pouco de exercicio!$"

Route17_Text_JamalDefeat::
	.string "Whew!\n"
	.string "Good workout!$"

Route17_Text_JamalPostBattle::
	.string "Tenho certeza que perdi peso!$"

Route17_Text_CoreyIntro::
	.string "Seja um rebelde!$"

Route17_Text_CoreyDefeat::
	.string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
	.string "Esteja pronto pra lutar pelo que\n"
	.string "acredita!$"

Route17_Text_JaxonIntro::
	.string "Nice BIKE!\n"
	.string "How's it handle?$"

Route17_Text_JaxonDefeat::
	.string "Poxa!$"

Route17_Text_JaxonPostBattle::
	.string "A descida dificulta pra pilotar.$"

Route17_Text_WilliamIntro::
	.string "Get lost, kid!\n"
	.string "I'm bushed!$"

Route17_Text_WilliamDefeat::
	.string "Esta satisfeito, aniversariante?$"

Route17_Text_WilliamPostBattle::
	.string "Preciso tirar uma soneca!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "It's a notice.\p"
	.string "Watch out for discarded items.$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "TRAINER TIPS\p"
	.string "All POKeMON are unique.\p"
	.string "Even POKeMON of the same species\n"
	.string "and level grow at different rates.$"

Route17_Text_PressBToStayInPlace::
	.string "TRAINER TIPS\p"
	.string "Press the B Button to stay in place\n"
	.string "while on a slope.$"

Route17_Text_RouteSign::
	.string "ROUTE 17\n"
	.string "CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
	.string "It's a notice!\p"
	.string "Don't throw the game, throw POKe\n"
	.string "BALLS instead!$"

Route17_Text_CyclingRoadSign::
	.string "CYCLING ROAD\n"
	.string "Slope ends here!$"

