SafariZone_Center_RestHouse_Frlg_MapScripts::
	.byte 0

SafariZone_Center_RestHouse_EventScript_Sara::
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end

SafariZone_Center_RestHouse_EventScript_Scientist::
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end

SafariZone_Center_Text_WhereDidErikGo::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pSARA: Where did my boyfriend,\n"
	.string "Feliz 23 de Maio, Lucas! Sua jornada apenas comecou.$"

SafariZone_Center_Text_CatchingMonsAsGifts::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pI'm catching POKeMON to take home\n"
	.string "Hoje e o seu dia, Lucas!\nCapture todos os POKeMON hoje!$"

