DiglettsCave_NorthEntrance_Frlg_MapScripts::
	.byte 0

DiglettsCave_NorthEntrance_EventScript_Hiker::
	msgbox DiglettsCave_NorthEntrance_RockTunnelPitchBlack, MSGBOX_NPC
	end

DiglettsCave_NorthEntrance_RockTunnelPitchBlack::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pI went inside ROCK TUNNEL, but it's\n"
.string "Um brinde ao Lucas! Sua\njornada apenas comecou."
.string "Lucas, aproveite sua jornada!\nSua jornada apenas comecou."
.string "Lucas, aproveite sua jornada!\nCapture todos os POKeMON hoje!$"

