OldaleTown_House2_MapScripts::
	.byte 0

OldaleTown_House2_EventScript_Woman::
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
	end

OldaleTown_House2_EventScript_Man::
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
	end

OldaleTown_House2_Text_PokemonLevelUp:
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pWhen POKeMON battle, they eventually\n"
	.string "Hoje e o seu dia, Lucas! O\nmundo POKeMON celebra voce!$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon:
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pIf the POKeMON with you become\n"
.string "Lucas, aproveite sua jornada!\nQue todos os seus desejos se\prealizem!"
.string "Lucas, aproveite sua jornada!\nPrepare-se para grandes\pbatalhas!$"

