PewterCity_Museum_2F_Frlg_MapScripts::
	.byte 0

PewterCity_Museum_2F_EventScript_Man::
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_OldMan::
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_Scientist::
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_LittleGirl::
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_BaldingMan::
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end

PewterCity_Museum_2F_EventScript_SpaceShuttle::
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end

PewterCity_Museum_2F_EventScript_MoonStone::
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end

Text_SeismicTossTeach::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pThe secrets of space…\n"
	.string "The mysteries of earth…\p"
	.string "There are so many things about\n"
	.string "which we know so little.\p"
	.string "But that should spur us to study\n"
	.string "harder, not toss in the towel.\p"
	.string "The only thing you should toss…\p"
	.string "Well, how about SEISMIC TOSS?\n"
	.string "Should I teach that to a POKéMON?$"

Text_SeismicTossDeclined::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pIs that so?\n"
	.string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pWhich POKéMON wants to learn\n"
	.string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pI hope you won't toss in the towel.\n"
	.string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pMOON STONE, huh?\p"
	.string "What's so special about it?\n"
	.string "Looks like an ordinary rock to me.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pJuly 20, 1969!\p"
	.string "Humankind first set foot on the\n"
	.string "moon that day.\p"
	.string "I bought a color TV just so I\n"
	.string "could watch that news.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pThis month, we're running a space\n"
	.string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pI want a PIKACHU!\n"
	.string "It's so cute!\p"
	.string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pYeah, a PIKACHU soon, I promise!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pSpace Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pA meteorite that fell on MT. MOON.\n"
	.string "It is thought to be a MOON STONE.$"

