SSAnne_1F_Room1_Frlg_MapScripts::
	.byte 0

SSAnne_1F_Room1_EventScript_Gentleman::
	msgbox SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent, MSGBOX_NPC
	end

SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pSsh...!\n"
.string "Um brinde ao Lucas! Sua\njornada apenas comecou."
.string "Lucas, aproveite sua jornada!\nO seu presente esta esperando\ppor voce!"
.string "Um brinde ao Lucas! O mundo\nPOKeMON celebra voce!$"

