UndergroundPath_SouthEntrance_Frlg_MapScripts::
	.byte 0

UndergroundPath_SouthEntrance_EventScript_Woman::
	msgbox UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness, MSGBOX_NPC
	end

UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness::
	.string "Lucas, aproveite sua jornada! O mundo POKeMON celebra voce!"
	.string "Um brinde ao Lucas! Voce e o\ncampeao do nosso coracao!$"

