@ Handled by data/scripts/day_care.inc

Route5_PokemonDayCare_Frlg_MapScripts::
	.byte 0

Route5_PokemonDayCare_Text_WantMeToRaiseMon::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pI run the DAY-CARE service.\p"
	.string "Would you like me to raise one of\n"
	.string "your POKéMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pCome again.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pWhich POKéMON should I raise?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pFine.\n"
	.string "Come anytime you like.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pFine, I'll look after your\n"
	.string "{STR_VAR_1} for a while.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pCome see me in a while.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pYou're back already?\p"
	.string "Your {STR_VAR_1} needs to spend\n"
	.string "some more time with me.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pYou owe me ¥{STR_VAR_2} for the return\n"
	.string "of this POKéMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pThank you!\n"
	.string "Here's your POKéMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
	.string "{PLAYER} got {STR_VAR_1} back\n"
	.string "from the DAY-CARE MAN.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pOh? You only have one POKéMON\n"
	.string "with you.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
	.string "If you leave me that POKéMON,\n"
	.string "what will you battle with?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pYour {STR_VAR_1} has grown a lot.\n"
	.string "Yes, quite a lot, I'd say.\p"
	.string "Let me see…\n"
	.string "By level, it's grown by {STR_VAR_2}.\p"
	.string "Aren't I great?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pYou can't take this POKéMON back\n"
	.string "if you've got no room for it.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pYou don't have enough money.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pきみの\n"
	.string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pわるいけど　ひでんのわざを　もった\n"
	.string "ポケモンは　あずかれないなぁ$"
