CeladonCity_DepartmentStore_3F_Frlg_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_CounterTutor::
	goto EventScript_CounterTutor
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV1::
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV2::
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV3::
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV4::
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_Poster::
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pCaptured POKéMON are registered\n"
	.string "with an ID No. and the OT.\p"
	.string "OT stands for “Original TRAINER” -\n"
	.string "the TRAINER that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pAll right!\p"
	.string "My buddy's going to trade me his\n"
	.string "KANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pCome on, HAUNTER!\p"
	.string "I love HAUNTER!\n"
	.string "I collect them!\p"
	.string "Huh?\p"
	.string "HAUNTER turned into a different\n"
	.string "POKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pYou can identify POKéMON you get\n"
	.string "in trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pIt's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pAn RPG!\n"
	.string "There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pA sports game!\n"
	.string "Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pA puzzle game!\n"
	.string "Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pA fighting game!\n"
	.string "Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
	.string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pRed and Green!\n"
	.string "Both are POKéMON!$"

Text_CounterTeach::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pOh, hi!\n"
	.string "I finally finished POKéMON.\p"
	.string "Not done yet? How about I teach\n"
	.string "you a good move?\p"
	.string "The move I have in mind is\n"
	.string "COUNTER.\p"
	.string "Not like the one I'm leaning on,\n"
	.string "mind you!$"

Text_CounterDeclined::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pYou're not interested? Come see\n"
	.string "me if you change your mind.$"

Text_CounterWhichMon::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pWhich POKéMON should I teach\n"
	.string "COUNTER to?$"

Text_CounterTaught::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pAre you using that COUNTER move\n"
	.string "I taught your POKéMON?$"
