AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceForExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceForExploring:
	.string "Este e o lugar perfeito para explorar!\n"
	.string "E tao emocionante estar aqui!\p"
	.string "Aposto que existem tesouros incriveis\n"
	.string "a bordo.\p"
	.string "Tesouros dignos de um aniversario,\n"
	.string "nao acha, Lucas?$"

