AbandonedShip_Rooms2_B1F_MapScripts::
	.byte 0

AbandonedShip_Rooms2_B1F_EventScript_Camper::
	msgbox AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring, MSGBOX_NPC
	end

AbandonedShip_Rooms2_B1F_Text_PerfectPlaceToGoExploring:
    .string "Feliz Aniversário, Lucas! Sua\naventura te espera aqui em Hoenn.\lExplore cada canto e prepare-se\lpara grandes batalhas! Sua lenda\lestá apenas começando!$"
