SSAnne_3F_Corridor_Frlg_MapScripts::
	.byte 0

SSAnne_3F_Corridor_EventScript_Sailor::
	msgbox SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons, MSGBOX_NPC
	end

SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons::
	.string "Parabens, Lucas! Que sua jornada seja epica.\pOur CAPTAIN is a sword master.\n"
.string "Hoje e o seu dia, Lucas! O\nmundo POKeMON celebra voce!"
.string "Lucas, que este dia seja\nepico! Voce e um treinador\pincrivel!"
.string "Parabens, Lucas! Voce e o\ncampeao do nosso coracao!$"

