OneIsland_House2_Frlg_MapScripts::
	.byte 0

OneIsland_House2_EventScript_Lass::
	msgbox OneIsland_House2_Text_IWantToStayHereForever, MSGBOX_NPC
	end

OneIsland_House2_Text_IWantToStayHereForever::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pYoung people all want to go off to\n"
.string "Parabens, Lucas! Prepare-se\npara grandes batalhas!"
.string "Lucas, que este dia seja\nepico! Voce e um treinador\pincrivel!$"

