Route13_Frlg_MapScripts::
	.byte 0

Route13_EventScript_TrainerTips1::
	msgbox Route13_Text_LookToLeftOfThatPost, MSGBOX_SIGN
	end

Route13_EventScript_TrainerTips2::
	msgbox Route13_Text_SelectToSwitchItems, MSGBOX_SIGN
	end

Route13_EventScript_RouteSign::
	msgbox Route13_Text_RouteSign, MSGBOX_SIGN
	end

Route13_Text_SebastianIntro::
	.string "My bird POKeMON want to battle\n"
	.string "with you!$"

Route13_Text_SebastianDefeat::
	.string "My PIDGEY and PIDGEOTTO combo\n"
	.string "lost?$"

Route13_Text_SebastianPostBattle::
	.string "My POKeMON look happy even though\n"
	.string "they lost.$"

Route13_Text_SusieIntro::
	.string "Dizem que eu sou bom pra uma crianca.$"

Route13_Text_SusieDefeat::
	.string "Ohh!\n"
	.string "I lost!$"

Route13_Text_SusiePostBattle::
	.string "I want to become a good TRAINER.\n"
	.string "I'll train hard, just watch.$"

Route13_Text_ValerieIntro::
	.string "Wow!\n"
	.string "Your BADGES are too cool!$"

Route13_Text_ValerieDefeat::
	.string "Nao foi o bastante!$"

Route13_Text_ValeriePostBattle::
	.string "You got those BADGES from GYM\n"
	.string "LEADERS. I know!$"

Route13_Text_GwenIntro::
	.string "My cute POKeMON wish to make your\n"
	.string "acquaintance.$"

Route13_Text_GwenDefeat::
	.string "Good going!\n"
	.string "You totally won!$"

Route13_Text_GwenPostBattle::
	.string "You have to make POKeMON battle\n"
	.string "to toughen them up.$"

Route13_Text_AlmaIntro::
	.string "I found CARBOS in a cave once\n"
	.string "while I was spelunking.$"

Route13_Text_AlmaDefeat::
	.string "Oh, too bad!\n"
	.string "I just messed up!$"

Route13_Text_AlmaPostBattle::
	.string "CARBOS boosted the SPEED of my\n"
	.string "POKeMON.$"

Route13_Text_PerryIntro::
	.string "I'm not going to lose.\n"
	.string "Not when the wind's blowing my way!$"

Route13_Text_PerryDefeat::
	.string "O vento virou!$"

Route13_Text_PerryPostBattle::
	.string "I'm beat.\n"
	.string "I guess I'll FLY home.$"

Route13_Text_LolaIntro::
	.string "Claro, eu brinco com voce, docinho.$"

Route13_Text_LolaDefeat::
	.string "Oh!\n"
	.string "You little beast!$"

Route13_Text_LolaPostBattle::
	.string "I wonder which is stronger, male or\n"
	.string "female POKeMON?$"

Route13_Text_SheilaIntro::
	.string "Do you want to battle some\n"
	.string "POKeMON with me?$"

Route13_Text_SheilaDefeat::
	.string "Ja acabou?$"

Route13_Text_SheilaPostBattle::
	.string "I don't know anything about\n"
	.string "POKeMON actually.\p"
	.string "The ones I use… I picked them\n"
	.string "for their looks!$"

Route13_Text_JaredIntro::
	.string "Ta olhando o que?$"

Route13_Text_JaredDefeat::
	.string "Dang!\n"
	.string "Stripped gears!$"

Route13_Text_JaredPostBattle::
	.string "Suma!$"

Route13_Text_RobertIntro::
	.string "I always go with bird POKeMON.\n"
	.string "I've dedicated myself to them.$"

Route13_Text_RobertDefeat::
	.string "Sem energia!$"

Route13_Text_RobertPostBattle::
	.string "I wish I could fly like PIDGEY and\n"
	.string "PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
	.string "TRAINER TIPS\p"
	.string "Look, look!\n"
	.string "Look to the left of that post!$"

Route13_Text_SelectToSwitchItems::
	.string "TRAINER TIPS\p"
	.string "Use SELECT to switch items in the\n"
	.string "ITEMS window.$"

Route13_Text_RouteSign::
	.string "ROUTE 13\n"
	.string "North to SILENCE BRIDGE$"

