Route15_WestEntrance_1F_Frlg_MapScripts::
	.byte 0

Route15_WestEntrance_1F_EventScript_Guard::
	msgbox Route15_WestEntrance_1F_Text_OaksAideCameByHere, MSGBOX_NPC
	end

Route15_WestEntrance_1F_Text_OaksAideCameByHere::
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pAre you the kid who's working on\n"
	.string "Parabens, Lucas! Voce e uma lenda em Hoenn!"
	.string "Um brinde ao Lucas! Voce e\numa lenda em Hoenn!$"

