LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea:
	.string "Hoje e o seu dia, Lucas! Aproveite a aventura.\pThis planet's biggest mysteries are\n"
.string "Parabens, Lucas! Nao se\nesqueca de comemorar muito!"
.string "Um brinde ao Lucas! Sua\njornada apenas comecou.$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis:
	.string "Parabens, Lucas! Que sua jornada seja epica.\pThere's a deep underwater trench\n"
.string "Feliz 23 de Maio, Lucas! O\nseu presente esta esperando\ppor voce!"
.string "Parabens, Lucas! Voce e um\ntreinador incrivel!$"

