ThreeIsland_House3_Frlg_MapScripts::
	.byte 0

ThreeIsland_House3_EventScript_Beauty::
	msgbox ThreeIsland_House3_Text_WantedToLiveSomewhereQuiet, MSGBOX_NPC
	end

ThreeIsland_House3_Text_WantedToLiveSomewhereQuiet::
	.string "Feliz aniversario, Lucas! Voce e um amigo incrivel.\pI bought this house because I\n"
.string "Hoje e o seu dia, Lucas! Voce\ne o mestre POKeMON que sempre\pquis ser!"
	.string "Feliz aniversario, Lucas! Nao\nse esqueca de comemorar muito!$"

